/**
 * Hotspot geometry for the masala dabba photograph.
 *
 * GENERATED by scripts/build-dabba.mjs — do not hand-edit. The numbers are
 * measured from the photograph, so they are only valid for the asset that
 * produced them. If the tin image changes, run `npm run build:dabba` again.
 *
 * Each centre is the middle of the largest disc that fits inside that well, as a
 * percentage of the image box. A seven-fold ring fitted to the same wells agrees
 * to within 1.28% of frame width, which is the check that the photograph is a
 * clean flat-lay. Order is clockwise from the 12 o'clock well and matches
 * `wells` in src/data/story.ts.
 */
/**
 * The filename carries a hash of the image contents, so replacing the photograph
 * changes the URL. Without that, Next's image optimizer keeps serving its cached
 * rendering of the old file, alpha channel included, and the change appears not
 * to have happened.
 */
export const DABBA_IMAGE = "/dabba/dabba.7625a01d.webp";

export type WellHotspot = {
  /** centre, as a percentage of the image box */
  left: number;
  top: number;
  /** radius, as a percentage of the image box width */
  radius: number;
};

export const wellHotspots: WellHotspot[] = [
  { left: 49.67, top: 18.92, radius: 13.31 }, // turmeric
  { left: 75.75, top: 32.08, radius: 13.25 }, // red-chilli
  { left: 80, top: 60.58, radius: 12.41 }, // dhana-jeeru
  { left: 62.17, top: 80.83, radius: 11.58 }, // cumin
  { left: 37, top: 80.67, radius: 11.58 }, // mustard
  { left: 19.75, top: 60.33, radius: 12.27 }, // hing
  { left: 24.08, top: 32.42, radius: 13 }, // garam-masala
];
