// GENERATED by scripts/import-shopify.mjs — do not edit by hand.
export type Department = { name: string; slug: string; image: string; count: number };

export const departments: Department[] = [
  {
    "name": "Bakery & Biscuits",
    "slug": "bakery-and-biscuits",
    "image": "/departments/bakery-and-biscuits.webp",
    "count": 42
  },
  {
    "name": "Chocolates & Candies",
    "slug": "chocolates-and-candies",
    "image": "/departments/chocolates-and-candies.webp",
    "count": 8
  },
  {
    "name": "Cosmetics",
    "slug": "cosmetics",
    "image": "/departments/cosmetics.webp",
    "count": 68
  },
  {
    "name": "Dals & Pulses",
    "slug": "dals-and-pulses",
    "image": "/departments/dals-and-pulses.webp",
    "count": 20
  },
  {
    "name": "Drinks",
    "slug": "drinks",
    "image": "/departments/drinks.webp",
    "count": 2
  },
  {
    "name": "Dry Fruits",
    "slug": "dry-fruits",
    "image": "/departments/dry-fruits.webp",
    "count": 10
  },
  {
    "name": "Festive & Decorative Products",
    "slug": "festive-and-decorative-products",
    "image": "/departments/festive-and-decorative-products.webp",
    "count": 106
  },
  {
    "name": "Flours",
    "slug": "flours",
    "image": "/departments/flours.webp",
    "count": 42
  },
  {
    "name": "Food Colors & Essence",
    "slug": "food-colors-and-essence",
    "image": "/departments/food-colors-and-essence.webp",
    "count": 5
  },
  {
    "name": "Frozen Foods",
    "slug": "frozen-foods",
    "image": "/departments/frozen-foods.webp",
    "count": 36
  },
  {
    "name": "Games & Sports",
    "slug": "games-and-sports",
    "image": "/departments/games-and-sports.webp",
    "count": 6
  },
  {
    "name": "Health & Hygiene",
    "slug": "health-and-hygiene",
    "image": "/departments/health-and-hygiene.webp",
    "count": 60
  },
  {
    "name": "Herbs & Spices",
    "slug": "herbs-and-spices",
    "image": "/departments/herbs-and-spices.webp",
    "count": 176
  },
  {
    "name": "Home Decor",
    "slug": "home-decor",
    "image": "/departments/home-decor.webp",
    "count": 1
  },
  {
    "name": "Household Cleaning",
    "slug": "household-cleaning",
    "image": "/departments/household-cleaning.webp",
    "count": 12
  },
  {
    "name": "Instant Food",
    "slug": "instant-food",
    "image": "/departments/instant-food.webp",
    "count": 16
  },
  {
    "name": "Juices & Pulps",
    "slug": "juices-and-pulps",
    "image": "/departments/juices-and-pulps.webp",
    "count": 7
  },
  {
    "name": "Kitchenware",
    "slug": "kitchenware",
    "image": "/departments/kitchenware.webp",
    "count": 88
  },
  {
    "name": "Mouth Freshner",
    "slug": "mouth-freshner",
    "image": "/departments/mouth-freshner.webp",
    "count": 55
  },
  {
    "name": "Noodles",
    "slug": "noodles",
    "image": "/departments/noodles.webp",
    "count": 4
  },
  {
    "name": "Oils & Ghee",
    "slug": "oils-and-ghee",
    "image": "/departments/oils-and-ghee.webp",
    "count": 6
  },
  {
    "name": "Papad",
    "slug": "papad",
    "image": "/departments/papad.webp",
    "count": 37
  },
  {
    "name": "Pickles",
    "slug": "pickles",
    "image": "/departments/pickles.webp",
    "count": 51
  },
  {
    "name": "Religious Items",
    "slug": "religious-items",
    "image": "/departments/religious-items.webp",
    "count": 135
  },
  {
    "name": "Rice & Grains",
    "slug": "rice-and-grains",
    "image": "/departments/rice-and-grains.webp",
    "count": 30
  },
  {
    "name": "Sauces & Chutnies",
    "slug": "sauces-and-chutnies",
    "image": "/departments/sauces-and-chutnies.webp",
    "count": 25
  },
  {
    "name": "Snacks",
    "slug": "snacks",
    "image": "/departments/snacks.webp",
    "count": 59
  },
  {
    "name": "Sugar & Jaggery",
    "slug": "sugar-and-jaggery",
    "image": "/departments/sugar-and-jaggery.webp",
    "count": 4
  },
  {
    "name": "Sweets & Desserts",
    "slug": "sweets-and-desserts",
    "image": "/departments/sweets-and-desserts.webp",
    "count": 43
  },
  {
    "name": "Tea & Coffee",
    "slug": "tea-and-coffee",
    "image": "/departments/tea-and-coffee.webp",
    "count": 4
  }
];
